# Generated by Django 6.0.3 on 2026-06-19 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_user_role_technicianapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
